# Generated by Django 3.1.7 on 2021-03-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.PositiveSmallIntegerField(unique=True, verbose_name='Последовательность вывода блоков на странице')),
            ],
            options={
                'ordering': ('sorting',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page_structures.block')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page_structures.block')),
            ],
        ),
    ]
