# Generated by Django 3.1.7 on 2021-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_structures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='block',
            name='sorting',
            field=models.PositiveSmallIntegerField(help_text='Последовательность вывода блоков на странице', unique=True),
        ),
    ]
